# Make sure to rename this file to config.ini before you use the bot

Bot:
  token: # Put your bot token here!!!!!!

Cogs:
  # Cogs that the bot shouldn't load, example:
  # blacklist:
  #   -reminder
  #   -general
  blacklist: